name: example
description: An example for flutter_pseudolocalizor package.
version: 0.4.0
author: James Leahy <defuncart@gmail.com>
homepage: https://github.com/defuncart/flutter_pseudolocalizor

environment:
  sdk: ">=2.6.0 <3.0.0"

dev_dependencies:
  flutter_pseudolocalizor:
    path: ../

flutter_pseudolocalizor:
  input_filepath: "test.csv"
  replace_base: false
  use_brackets: true
  text_expansion_ratio: 1.4
  languages_to_generate:
    - de
    - es
    - fr
    - it
    - pl
    - pt
    - ru
    - tr
  csv_settings:
    delimiter: ";"
    column_index: 1
  patterns_to_ignore:
    - '%(\S*?)\$[ds]'
    - 'Flutter'
  line_numbers_to_ignore:
    - 2
