name: flutter_pseudolocalizor
description: A Pseudolocalization tool for Flutter and Dart which generates pseudo, nonsensical translations for multiple languages from a given English source.
version: 0.3.0
homepage: https://github.com/defuncart/flutter_pseudolocalizor
repository: https://github.com/defuncart/flutter_pseudolocalizor
issue_tracker: https://github.com/defuncart/flutter_pseudolocalizor/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.1.6
  yaml: ^2.2.0

dev_dependencies:
  test: ^1.15.0
  pedantic: ^1.9.0
