/// Settings for LatinExtendedBlock.latinExtendedC
class LatinExtendedC {
  /// An array of special characters
  static const specialCharacters = [
    'Ⱡ',
    'ⱡ',
    'Ɫ',
    'Ᵽ',
    'Ɽ',
    'ⱥ',
    'ⱦ',
    'Ⱨ',
    'ⱨ',
    'Ⱪ',
    'ⱪ',
    'Ⱬ',
    'ⱬ',
    'Ɑ',
    'Ɱ',
    'Ɐ',
    'Ɒ',
    'ⱱ',
    'Ⱳ',
    'ⱳ',
    'ⱴ',
    'Ⱶ',
    'ⱶ',
    'ⱷ',
    'ⱸ',
    'ⱹ',
    'ⱺ',
    'ⱻ',
    'ⱼ',
    'ⱽ',
    'Ȿ',
    'Ɀ',
  ];

  /// A dictionary of mapping characters
  static const mappingCharacters = {
    'a': ['ⱥ', 'Ɑ'],
    'A': ['Ɐ'],
    'D': ['Ɒ'],
    'e': ['ⱸ', 'ⱻ'],
    'h': ['ⱨ'],
    'H': ['Ⱨ', 'Ⱶ'],
    'i': ['ⱶ'],
    'j': ['ⱼ'],
    'k': ['ⱪ'],
    'K': ['Ⱪ'],
    'l': ['ⱡ', 'ⱹ'],
    'L': ['Ⱡ', 'Ɫ'],
    'M': ['Ɱ'],
    'o': ['ⱷ', 'ⱺ'],
    'P': ['Ᵽ'],
    'R': ['Ɽ'],
    'S': ['Ȿ'],
    't': ['ⱦ'],
    'v': ['ⱱ', 'ⱴ', 'ⱽ'],
    'w': ['ⱳ'],
    'W': ['Ⱳ'],
    'z': ['ⱬ'],
    'Z': ['Ⱬ', 'Ɀ'],
  };
}
