/// Settings for LatinExtendedBlock.superscriptsSubscripts
abstract class SuperscriptsSubscripts {
  /// An array of special characters
  static const specialCharacters = [
    '⁰',
    'ⁱ',
    '¹',
    '²',
    '³',
    '⁴',
    '⁵',
    '⁶',
    '⁷',
    '⁸',
    '⁹',
    '⁺',
    '⁻',
    '⁼',
    '⁽',
    '⁾',
    'ⁿ',
    '₀',
    '₁',
    '₂',
    '₃',
    '₄',
    '₅',
    '₆',
    '₇',
    '₈',
    '₉',
    '₊',
    '₋',
    '₌',
    '₍',
    '₎',
    'ₐ',
    'ₑ',
    'ₒ',
    'ₓ',
    'ₔ',
  ];

  /// A dictionary of mapping characters
  static const mappingCharacters = {
    '0': ['⁰', '₀'],
    '1': ['¹', '₁'],
    '2': ['²', '₂'],
    '3': ['³', '₃'],
    '4': ['⁴', '₄'],
    '5': ['⁵', '₅'],
    '6': ['⁶', '₆'],
    '7': ['⁷', '₇'],
    '8': ['⁸', '₈'],
    '9': ['⁹', '₉'],
    '+': ['⁺', '₊'],
    '-': ['⁻', '₋'],
    '=': ['⁼', '₌'],
    '(': ['⁽', '₍'],
    ')': ['⁾', '₎'],
    'a': ['ₐ'],
    'e': ['ₑ', 'ₔ'],
    'i': ['ⁱ'],
    'n': ['ⁿ'],
    'o': ['ₒ'],
    'x': ['ₓ'],
  };
}
