name: pull_request_ci
on: pull_request
jobs:
  lint-unit-tests:
    name: Lint + Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
      - name: Install packages
        run: dart pub get
      - name: Formatting
        run: dart format . -l 80 --set-exit-if-changed
      - name: Lint
        run: dart analyze
      - name: Unit tests
        run: dart test
